import type { GeneralTodoOverviewResponse } from "./types";

export const mockOverview: GeneralTodoOverviewResponse = {
  folders: [
    { id: 1, name: "인박스", username: "arkuser", sortOrder: 0 },
    { id: 2, name: "업무", username: "arkuser", sortOrder: 1 },
    { id: 3, name: "생활", username: "arkuser", sortOrder: 2 },
  ],
  categories: [
    {
      id: 11,
      name: "빠르게 처리",
      color: "#5C7CFA",
      folderId: 1,
      username: "arkuser",
      sortOrder: 0,
      viewMode: "LIST",
    },
    {
      id: 12,
      name: "나중에 보기",
      color: "#E599F7",
      folderId: 1,
      username: "arkuser",
      sortOrder: 1,
      viewMode: "KANBAN",
    },
    {
      id: 21,
      name: "회의",
      color: "#845EF7",
      folderId: 2,
      username: "arkuser",
      sortOrder: 0,
      viewMode: "LIST",
    },
    {
      id: 22,
      name: "프로젝트",
      color: "#91A7FF",
      folderId: 2,
      username: "arkuser",
      sortOrder: 1,
      viewMode: "KANBAN",
    },
    {
      id: 31,
      name: "집안일",
      color: "#63E6BE",
      folderId: 3,
      username: "arkuser",
      sortOrder: 0,
      viewMode: "LIST",
    },
    {
      id: 32,
      name: "건강",
      color: "#FFD43B",
      folderId: 3,
      username: "arkuser",
      sortOrder: 1,
      viewMode: "LIST",
    },
  ],
  todos: [
    {
      id: 101,
      title: "메일함 정리",
      description: "불필요한 뉴스레터 정리하기",
      folderId: 1,
      categoryId: 11,
      username: "arkuser",
      dueDate: "2024-07-03T09:00",
      completed: false,
      createdAt: "2024-06-30T10:00",
      updatedAt: "2024-06-30T10:00",
    },
    {
      id: 102,
      title: "이력제 폴더 구조 구상",
      description: null,
      folderId: 1,
      categoryId: 12,
      username: "arkuser",
      dueDate: null,
      completed: false,
      createdAt: "2024-06-29T11:30",
      updatedAt: "2024-06-29T11:30",
    },
    {
      id: 201,
      title: "주간 회의 안건 정리",
      description: "디자인 QA 논의 포함",
      folderId: 2,
      categoryId: 21,
      username: "arkuser",
      dueDate: "2024-07-02T14:00",
      completed: false,
      createdAt: "2024-06-27T09:00",
      updatedAt: "2024-06-28T09:10",
    },
    {
      id: 202,
      title: "신규 기능 와이어 작성",
      description: "모바일 대응 영역 우선",
      folderId: 2,
      categoryId: 22,
      username: "arkuser",
      dueDate: "2024-07-05T18:00",
      completed: true,
      createdAt: "2024-06-25T13:00",
      updatedAt: "2024-06-30T16:30",
    },
    {
      id: 301,
      title: "주말 장보기",
      description: "야채, 닭가슴살, 프로틴 바",
      folderId: 3,
      categoryId: 31,
      username: "arkuser",
      dueDate: "2024-07-06T11:00",
      completed: false,
      createdAt: "2024-06-30T08:00",
      updatedAt: "2024-06-30T08:00",
    },
    {
      id: 302,
      title: "필라테스 예약",
      description: null,
      folderId: 3,
      categoryId: 32,
      username: "arkuser",
      dueDate: null,
      completed: false,
      createdAt: "2024-06-28T19:00",
      updatedAt: "2024-06-28T19:00",
    },
  ],
};
