export default {
  GET_MY_INFORMATION: "GET_MY_INFORMATION",
  GET_FRIENDS: "GET_FRIENDS",
  GET_CHARACTERS: "GET_CHARACTERS",
  GET_CUBE_REWARD: "GET_CUBE_REWARD",
  GET_COMMENTS: "GET_COMMENTS",
  GET_OFFICIAL_NOTICES: "GET_OFFICIAL_NOTICES",
  GET_NOTICES: "GET_NOTICES",
  GET_NOTICE: "GET_NOTICE",
} as const;
